FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# storm

Mock api para Viajabessa, empressa fictícia que vende pacotes turísticos.

# Storm API Root [/]

This resource does not have any attributes. Instead it offers the initial
API affordances in the form of the links in the JSON body.

It is recommend to follow the “url” link values,
[Link](https://tools.ietf.org/html/rfc5988) or Location headers where
applicable to retrieve resources. Instead of constructing your own URLs,
to keep your client decoupled from implementation details.

## Retrieve the Entry Point [GET]

+ Response 200 (application/json)

        {
            "pacotes_url": "/pacotes"
        }

## Group Pacotes

Recurso relacionado a pacotes turísticos

## Pacotes [/pacotes/{pacote_id}]

A Question object has the following attributes:

+ destino
+ published_at - Um timestamp de quando o pacote foi publicado no formato "yyyy-MM-dd HH:mm:ss"
+ preco
+ imagem - Uma URL para uma imagem
+ descricao

+ Parameters
    + pacote_id: 1 (required, number) - ID do pacote na forma de um número inteiro

### Ver detalhes de um pacote [GET]

Essa informação não é enviada juntamente com a lista de pacotes pois a mesma não é exibida na inteface de usuário ao ser carregada e por considerar que, na visão detalhada, outros atributos podem vir a ser necessários no futuro.

+ Response 200 (application/json)

        {
            "descricao": "As belezas naturais do Rio de Janeiro já são conhecidas por todos, mas basta uma visita à cidade maravilhosa para comprovar que há muito para se encantar. A combinação de serra e mar forma uma das paisagens mais belas do mundo, principalmente quando a cidade é vista de pontos turísticos como Cristo Redentor, Pão de Açúcar e Pedra da Gávea. Além da natureza generosa, o Rio de Janeiro brinda os turistas com atrações únicas, como a Baía de Guanabara, o Aterro do Flamengo, as praias de Copacabana e Ipanema, a Lagoa Rodrigo de Freitas e os bairros boêmios da Lapa, Botafogo e Leblon."
        }

## Pacotes Collection [/pacotes]


### Listar todos os Pacotes [GET]

+ Response 200 (application/json)
    + Body

            [
                {
                    "destino": "Rio de Janeiro",
                    "published_at": "2015-07-02 08:40:51",
                    "url": "/pacotes/1",
                    "imagem": "http://www.braziladventuretours.com/admin/uploads/noticias/slide/13415477241233ed55138ae5ff0bac4e9500c95349.jpg",
                    "preco": 799.99
                },
                {
                    "destino": "Paris",
                    "published_at": "2015-07-01 06:45:51",
                    "url": "/pacotes/2",
                    "imagem": "http://farm9.staticflickr.com/8539/8628276102_568cf9bdcf_z.jpg",
                    "preco": 1999.99
                },
                {
                    "destino": "Viena",
                    "published_at": "2015-05-21 16:45:55",
                    "url": "/pacotes/3",
                    "imagem": "http://farm3.staticflickr.com/2490/3769162335_533df3fe0d_z.jpg",
                    "preco": 2999.99
                },
                {
                    "destino": "Nova Deli",
                    "published_at": "2015-05-21 16:45:55",
                    "url": "/pacotes/4",
                    "imagem": "http://farm4.static.flickr.com/3660/3618711249_4c9fceb5f7_m.jpg",
                    "preco": 709.99
                },
                {
                    "destino": "Copenhague",
                    "published_at": "2015-05-21 16:45:55",
                    "url": "/pacotes/5",
                    "imagem": "http://farm4.staticflickr.com/3282/2912999260_b623d7cf8c_o.jpg",
                    "preco": 5999.99
                }
            ]
