FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# storm

Mock api para Viajabessa, empressa fictícia que vende pacotes turísticos.

# Polls API Root [/]

This resource does not have any attributes. Instead it offers the initial
API affordances in the form of the links in the JSON body.

It is recommend to follow the “url” link values,
[Link](https://tools.ietf.org/html/rfc5988) or Location headers where
applicable to retrieve resources. Instead of constructing your own URLs,
to keep your client decoupled from implementation details.

## Retrieve the Entry Point [GET]

+ Response 200 (application/json)

        {
            "pacotes_url": "/pacotes"
        }

## Group Pacotes

Recurso relacionado a pacotes turísticos

## Pacotes [/pacotes/{pacote_id}]

A Question object has the following attributes:

+ destino
+ published_at - Um timestamp de quando o pacote foi publicado no formato "yyyy-MM-dd HH:mm:ss"
+ preco
+ imagem - Uma URL para uma imagem
+ descricao

+ Parameters
    + pacote_id: 1 (required, number) - ID do pacote na forma de um número inteiro

### View a Questions Detail [GET]

+ Response 200 (application/json)

        {
            "destino": "Rio de Janeiro",
            "published_at": "2014-11-11 08:40:51",
            "url": "/pacotes/1",
            "imagem": "http://www.braziladventuretours.com/admin/uploads/noticias/slide/13415477241233ed55138ae5ff0bac4e9500c95349.jpg"
            "descricao": "As belezas naturais do Rio de Janeiro já são conhecidas por todos, mas basta uma visita à cidade 
            maravilhosa para comprovar que há muito para se encantar. A combinação de serra e mar forma uma das paisagens 
            mais belas do mundo, principalmente quando a cidade é vista de pontos turísticos como Cristo Redentor, Pão de 
            Açúcar e Pedra da Gávea. Além da natureza generosa, o Rio de Janeiro brinda os turistas com atrações únicas, 
            como a Baía de Guanabara, o Aterro do Flamengo, as praias de Copacabana e Ipanema, a Lagoa Rodrigo de Freitas 
            e os bairros boêmios da Lapa, Botafogo e Leblon."
            "preco": ""
        }

## Choice [/questions/{question_id}/choices/{choice_id}]

+ Parameters
    + question_id: 1 (required, number) - ID of the Question in form of an integer
    + choice_id: 1 (required, number) - ID of the Choice in form of an integer

### Vote on a Choice [POST]

This action allows you to vote on a question's choice.

+ Response 201

    + Headers

            Location: /questions/1

## Questions Collection [/questions{?page}]

+ Parameters
    + page: 1 (optional, number) - The page of questions to return

### List All Questions [GET]

+ Response 200 (application/json)

    + Headers

            Link: </questions?page=2>; rel="next"

    + Body

            [
                {
                    "question": "Favourite programming language?",
                    "published_at": "2014-11-11T08:40:51.620Z",
                    "url": "/questions/1",
                    "choices": [
                        {
                            "choice": "Swift",
                            "url": "/questions/1/choices/1",
                            "votes": 2048
                        }, {
                            "choice": "Python",
                            "url": "/questions/1/choices/2",
                            "votes": 1024
                        }, {
                            "choice": "Objective-C",
                            "url": "/questions/1/choices/3",
                            "votes": 512
                        }, {
                            "choice": "Ruby",
                            "url": "/questions/1/choices/4",
                            "votes": 256
                        }
                    ]
                }
            ]

### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ question (string) - The question
+ choices (array[string]) - A collection of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2014-11-11T08:40:51.620Z",
                "url": "/questions/2",
                "choices": [
                    {
                        "choice": "Swift",
                        "url": "/questions/2/choices/1",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "url": "/questions/2/choices/2",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "url": "/questions/2/choices/3",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "url": "/questions/2/choices/4",
                        "votes": 0
                    }
                ]
            }
